quest:
  montant: 500
  complete-command: "say La quête de [player] est terminée!"

mysql:
  host: "mc-mysql"
  user: "root"
  password: "root"
  database : "quest"

quantity-range:
  min: 10
  max: 50


possible-items:
  - ACACIA_WOOD
  - ACACIA_PLANK
  - ACACIA_SLAB
  - ACACIA_FENCE
  - ACACIA_DOOR
  - ACACIA_STAIRS
  - BIRCH_WOOD
  - BIRCH_PLANK
  - BIRCH_SLAB
  - BIRCH_FENCE
  - BIRCH_DOOR
  - BIRCH_STAIRS
  - COBBLESTONE
  - STONE
  - STONE_SLAB
  - STONE_STAIRS
  - GRANITE
  - GRANITE_SLAB
  - GRANITE_STAIRS
  - DIAMOND
  - DIRT
  - GOLD_ORE
  - IRON_ORE
  - COAL_ORE
  - LAPIS_ORE
  - NETHER_QUARTZ_ORE
  - EMERALD_ORE
  - WOODEN_PLANK
  - OAK_WOOD
  - OAK_PLANK
  - OAK_SLAB
  - OAK_FENCE
  - OAK_STAIRS
  - SAND
  - SANDSTONE
  - SANDSTONE_SLAB
  - SANDSTONE_STAIRS
  - GLASS
  - GLASS_PANE
  - GRAVEL
  - MELON
  - CARROT
  - POTATO
  - WHEAT
  - BREAD
  - COOKED_BEEF
  - COOKED_CHICKEN
  - COOKED_PORKCHOP
  - COOKED_RABBIT
  - GOLDEN_APPLE
  - DIAMOND_SWORD
  - IRON_SWORD
  - STONE_SWORD
  - WOODEN_SWORD
  - BOW
  - ARROW
  - FISHING_ROD
  - PAINTING
  - TNT
  - ENCHANTED_BOOK
  - BOOK_AND_QUILL
  - LANTERN
  - COMPASS
  - CLOCK
  - FURNACE
  - CRAFTING_TABLE
  - CHEST
  - BED
  - IRON_BLOCK
  - GOLD_BLOCK
  - DIAMOND_BLOCK
  - EMERALD_BLOCK
  - NETHERITE_BLOCK
  - CARTOGRAPHY_TABLE
  - LOOM
  - SMITHING_TABLE
  - BARREL
  - SMOKER
  - COMPOSTER
  - ANVIL
  - GLOWSTONE
  - SOUL_SAND
  - SOUL_SOIL
  - QUARTZ_BLOCK
  - MAGMA_BLOCK
  - PRISMARINE
  - CONDUIT
  - CREEPER_HEAD
  - SKELETON_HEAD
  - ZOMBIE_HEAD
  - DRAGON_HEAD
  - MUSIC_DISC
  - POTION
  - SPLASH_POTION
  - LINGERING_POTION
  - TURTLE_EGG
  - BEE_NEST
  - BEEHIVE
  - BEESWAX
  - OAK_LEAVES
  - BIRCH_LEAVES
  - ACACIA_LEAVES
  - JUNGLE_LEAVES
  - SPRUCE_LEAVES
  - VINES
  - SEAGRASS
  - TALL_GRASS
  - LETTUCE
  - FERN
  - LILY_PAD
  - CAMPFIRE
  - SOUL_CAMPFIRE
  - FIRE
  - CANDLE
  - CANDLE_WHITE
  - CANDLE_ORANGE
  - CANDLE_MAGENTA
  - CANDLE_LIGHT_BLUE
  - CANDLE_YELLOW
  - CANDLE_LIME
  - CANDLE_PINK
  - CANDLE_GRAY
  - CANDLE_LIGHT_GRAY
  - CANDLE_CYAN
  - CANDLE_PURPLE
  - CANDLE_BLUE
  - CANDLE_BROWN
  - CANDLE_GREEN
  - CANDLE_RED
  - CANDLE_BLACK
  - OAK_LOG
  - BIRCH_LOG
  - SPRUCE_LOG
  - JUNGLE_LOG
  - DARK_OAK_LOG
  - CRIMSON_STEM
  - WARPED_STEM
  - MELON_SLICE
  - STICK
  - BONE
  - FEATHER
  - STRING
  - SUGAR
  - SUGAR_CANE
  - LEATHER
  - TNT_MINECART
  - MINECART
  - MELON_SEEDS
  - PUMPKIN_SEEDS
  - BAMBOO
  - COCONUT
  - NETHER_WART
  - GLISTERING_MELON
  - SPECKLED_MELON
  - BLAZE_POWDER
  - BLAZE_ROD
  - GHAST_TEAR
  - DRAGON_BREATH
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - CREEPER_SKULL
  - ZOMBIE_SKULL
  - BLAZE_SKULL
  - SPIDER_EYE
  - SPLIT_MUSHROOM
  - NETHER_STAR
  - TRIDENT
  - SHULKER_SHELL
  - SHULKER_BOX
  - HOPPER
  - DISPENSER
  - DROPPER
  - LEVER
  - REDSTONE
  - REPEATER
  - COMPARATOR
  - REDSTONE_TORCH
  - STONE_BUTTON
  - WOODEN_BUTTON
  - WOODEN_PRESSURE_PLATE
  - STONE_PRESSURE_PLATE
  - IRON_PRESSURE_PLATE
  - GOLD_PRESSURE_PLATE
  - OBSERVER
  - PISTON
  - STICKY_PISTON
  - SLIME_BLOCK
  - HONEY_BLOCK
  - CREEPER_EGG
  - ENDER_PEARL
  - ENDER_EYE
  - END_CRYSTAL
  - ENDER_CHEST
  - ELYTRA
  - CHORUS_FRUIT
  - CHORUS_FLOWER
  - PURPUR_BLOCK
  - PURPUR_PILLAR
  - PURPUR_SLAB
  - PURPUR_STAIRS
  - END_STONE
  - ENDER_PORTAL_FRAME
  - EYE_OF_ENDER
  - DRAGON_EGG
  - BEACON
  - OBSIDIAN
  - NETHER_PORTAL
  - SADDLE
  - HORSE_ARMOR
  - IRON_HORSE_ARMOR
  - GOLDEN_HORSE_ARMOR
  - DIAMOND_HORSE_ARMOR
  - JUNGLE_SAPLING
  - ACACIA_SAPLING
  - BIRCH_SAPLING
  - OAK_SAPLING
  - DARK_OAK_SAPLING
  - CRIMSON_SAPLING
  - WARPED_SAPLING
  - WHITE_WOOL
  - ORANGE_WOOL
  - MAGENTA_WOOL
  - LIGHT_BLUE_WOOL
  - YELLOW_WOOL
  - LIME_WOOL
  - PINK_WOOL
  - GRAY_WOOL
  - LIGHT_GRAY_WOOL
  - CYAN_WOOL
  - PURPLE_WOOL
  - BLUE_WOOL
  - BROWN_WOOL
  - GREEN_WOOL
  - RED_WOOL
  - BLACK_WOOL
  - WHITE_BANNER
  - ORANGE_BANNER
  - MAGENTA_BANNER
  - LIGHT_BLUE_BANNER
  - YELLOW_BANNER
  - LIME_BANNER
  - PINK_BANNER
  - GRAY_BANNER
  - LIGHT_GRAY_BANNER
  - CYAN_BANNER
  - PURPLE_BANNER
  - BLUE_BANNER
  - BROWN_BANNER
  - GREEN_BANNER
  - RED_BANNER
  - BLACK_BANNER


